spring:
  application:
    name: bomber
  datasource:
    url: jdbc:postgresql://localhost:5432/bomber_db
    username: bomber_user
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true